### ISSUE TITLE
How to set root password using the correct encryption version

### ISSUE THREAD

**Issue by Ranjith219** [ansible-lockdown/AMAZON2023-CIS#86] opened 2024-08-14 03:58 UTC
**Question**
I'm pretty new to Ansible and I have been trying this Ansible role. However, it's failing at the "Ensure root password is set" step and I'm unclear on how to set the password. I just cloned this repo, configured the tag in the playbook, and ran it. Please help me out. The error message is below.

    amazon-ebs.amz3-build: TASK [ace-os-hardening-ansible-cis-amnz-linux3 : Ensure root password is set] ***
    amazon-ebs.amz3-build: fatal: [default]: FAILED! => {"changed": false, "cmd": "passwd -S root | grep \"Password set, SHA512 crypt\"", "delta": "0:00:00.021461", "end": "2024-08-14 03:18:43.994469", "msg": "non-zero return code", "rc": 1, "start": "2024-08-14 03:18:43.973008", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

**Environment (please complete the following information):**

- Ansible Version: 2.10
- Host Python Version: Python 3.9
- Ansible Server Python Version: Python 3.9
- Additional Details:

**Comment by uk-bolly** [comment] 2024-08-14 06:52
hi @Ranjith219 

This is a test to ensure you have a root password set when you have a specific control enabled. In this case

You have rule 4.6.6 enabled this requires that you have a root password set (this is also the in the error output.

This will halt the playbook due to the fact it could break your system with that enabled and you not yet set a root password.
For amazon they generally don't set them but CIS recommends that you do.
You can either skip this particular control  changing the value to false for amzn2023cis_rule_4_6_6 or you could set a root password manually to enable this control to take place.

Hope that helps.

uk-bolly

**Comment by Ranjith219** [comment] 2024-08-14 13:41
Ah, that makes sense, thank you so much for clarification and quick response, appreciate it.

**Comment by uk-bolly** [comment] 2024-09-17 11:01
hi @Ranjith219

I believe the original issue has been resolved, i will therefore close this call.
The second question it looks like you maybe running on local host? Have you tried the same steps manually and able to reproduce?
Could it be the step before breaking it?
If you still have issues, if you can please raise a new request providing as much information as possible.

Many thanks

uk-bolly

**Closed by uk-bolly** 2024-09-17 11:01 UTC
Labels: question
